ur3e_gym: #namespace
    # General Agent parameters
    env_id: "UR3eDualTaskPipeCoatingEnv-v0"
    simulation: False

    ft_sensor: True
    # ft_topic: 'resense_ft/wrench'
    relative_to_ee: False
    robot_control_dt: 0.002
    agent_control_dt: 0.1
    reset_time: 1.0

    right_arm_rps: 4 # revolution per subtask
    steps_per_episode: 300
    
    ft_hist: True
    ft_size: 3
    wrench_hist_size: 12
    
    actor_class: "wave"

    rand_seed: 10   
    # initial conditions
    random_initial_pose: True
    rand_init_interval: 1
    # for each dimension define upper and lower bound from initial pose
    workspace: [[0.04,-0.04], [0.04, -0.04], [0.005, 0.02], [10, -10], [10, -10], [10, -10]]
    init_q: [1.7731, -1.8039, -0.9695, -0.3539, -0.2037, -0.0]

    init_q_pick: [1.8139, -1.7838, -1.0175, -0.328, -0.2441, -0.0]
    init_q_spreader: [1.7731, -1.8461, -0.9332, -0.3506, -0.2041, -0.0]
    
    task_initial_pose: [2.0018, -1.6728, -1.142, -0.321, -0.4322, 0.0]
    
    target_pose_uncertain: False
    uncertainty_std: [0.001, 0.0]

    # -0.17874, -0.27643, 0.55169
    # -0.36584, -0.27639, 0.55157
    target_pos: [-0.3527, -0.28003, 0.54222]
    target_pos_pick: [-0.35065, -0.278, 0.5428]
    target_pos_spreader: [-0.36, -0.28092, 0.54666]
    extra_ee: [0, 0, 0.1871, 0, 0, 0, 1]
    end_effector_points: [[0.,0.,0.]]
    
    # actions parameters 
    n_actions: 12
    
    # Reward parameters
    target_dims: [0,1,2,3,4,5]
    step_cost: -1.0
    success_reward: 100.0
        
# Controller parameters
ur3e_force_control:
    n_actions: 12
    robot_control_dt: 0.002
    
    max_speed: [0.01, 0.01, 0.01] # per agent action
    action_scale: [1., 1., 1.]

    max_force_torque: [10.0, 10.0, 10.0, 3.0, 3.0, 3.0]
    desired_force_torque: [0.0, 0.0, 0.0]
    
    # parallel control parameters
    pd_range_type: 'mult' # or 'sum'
    base_position_kp: [10.0, 10.0, 10.0]
    kpd_range: 2
    base_force_kp: [5.0e-2, 5.0e-2, 5.0e-2]
    kpi_range: 2
    
    alpha: [0.5,0.5,0.5] # keep a degree of compliance
    alpha_base: 0.6
    alpha_range: 0.3
