ur3e_force_control:
  desired_force_torque:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  max_force_torque:
  - 50
  - 50.0
  - 50.0
  - 5
  - 5
  - 5
  max_twist:
  - 1.0
  - 3.1415
ur3e_gym:
  action_type: slicing-3d
  actor_class: default
  agent_control_dt: 0.02
  auto_alpha: true
  basic_randomization: false
  batch_size: 1024
  controller_type: cartesian_compliance
  cost:
    alpha: 1.0e-10
    collision: -10
    done: 10
    l1: 0.1
    l2: 2.0
    step: -1
  ee_link: knife_center
  env_id: UR3eSlicingEnv-v1
  ft_hist: false
  goal_threshold:
  - 1.0
  - 0.002
  - 0.08
  init_q:
  - 1.3524
  - -1.5555
  - 1.7697
  - -1.7785
  - -1.5644
  - 1.3493
  last_action_as_obs: true
  lr: 0.01
  max_damping_range:
  - 0
  - 1
  max_distance:
  - 0.1
  - 0.1
  - 0.1
  - 0.785398
  - 0.785398
  - 1.5707
  max_friction_range:
  - 0
  - 2
  max_kd_range:
  - 1
  - 2
  max_kp_range:
  - 100000.0
  - 500000.0
  max_stiffness_range:
  - 500
  - 1200
  n_actions: 6
  namespace: b_bot
  normal_randomization: true
  normalize_velocity: true
  object_friction: 1
  object_initial_pose:
  - -0.12
  - 0.03
  - 0.875
  - 0
  - 0
  - 1.5707
  object_name: target_block_tmp
  object_stiffness: 600
  object_workspace:
  - - -0.05
    - 0.05
  - - -0.05
    - 0.05
  - - 0.08
    - 0.02
  - - -20
    - 20
  - - -20
    - 20
  - - -60
    - 60
  rand_seed: 123456
  random_initial_pose: false
  random_target_pose: false
  randomize_object_properties: true
  real_robot: false
  relative_to_ee: false
  reset_motion:
  - 0.0
  - 0
  - 0.035
  - 0
  - 0
  - 0
  reset_robot: true
  reset_time: 0.5
  reward_type: slicing
  robot_control_dt: 0.002
  steps_per_episode: 500
  successes_threshold: 10
  target_dims:
  - 0
  - 2
  - 4
  target_duration: 6
  target_pose:
  - 0.11
  - 0.5
  - 0.1565
  - -0.00812894
  - 0.70963372
  - -0.00882711
  - 0.70446859
  target_pose_uncertain: false
  termination_on_negative_reward: false
  termination_reward_threshold: -300
  test_mode: false
  uncertainty_std:
  - 0.001
  - 0.0
  update_interval: 2
  w_dist: 1.0
  w_force: 0.1
  w_jerkiness: 0.1
  mu1: 0.5
  mu2: 0.0
  mu3: 1.0
  workspace:
  - - 0
    - 0
  - - 0
    - 0
  - - 0.0
    - 0.02
  - - 0
    - 0
  - - 0
    - 0
  - - 0
    - 0
  workspace_limit:
  - 0.05
  - 0.1
  - 0.523599
  wrench_hist_size: 1
