ur3e_gym: #namespace
    # General Agent parameters
    env_id: "UR3ePegInHoleEnv-v1"
    controller_type: "parallel_position_force" # or "admittance"

    reset_robot: False
    real_robot: True
    test_mode: True

    ft_sensor: True
    relative_to_ee: False
    robot_control_dt: 0.002
    agent_control_dt: 0.05
    reset_time: 2.0
    # actions parameters 
    n_actions: 24
    action_type: "m24"
    object_centric: False
    ee_centric: False

    steps_per_episode: 500
    
    actor_class: "wave"
    ft_hist: True
    wrench_hist_size: 6
    duration_as_obs: False
    last_action_as_obs: True
    normalize_velocity: True

    rand_seed: 654789
    rand_interval: 1

    randomize_board_properties: False
    board_mu: 1.0
    board_mu2: 1.0
    board_stiffness: 1.0e+5
    max_mu_range: [1, 3]
    max_stiffness_range: [7.0e+4, 5.0e+5]
    max_scale_range: [1.05, 1.0]
    curriculum_learning: False
    
    uncertainty_error: False

    # initial conditions
    random_initial_pose: True
    # for each dimension define upper and lower bound from initial pose
    max_distance: [0.04, 0.04, 0.05, 0.785398, 0.785398, 1.5707]
    # workspace: [[-0.03,0.03], [-0.01, 0.03], [-0.01, -0.05], [10, -10], [10, -10], [30, -30]] # pegs
    # workspace: [[-0.02,0.02], [-0.01, 0.02], [-0.01, -0.03], [05, -05], [05, -05], [30, -30]] # pulley
    workspace: [[-0.02,0.02], [-0.01, 0.02], [-0.01, -0.04], [15, -1], [15, -15], [45, -45]] # pulley
    # init_q: [4.8078, -0.4738, 1.0339, -2.1498, 1.6118, 1.441] # vertical
    # init_q: [4.553589, -0.709045, 1.183532, -2.043256, 1.579103, 3.299792] # pulley
    # init_q: [4.809954, -0.572266, 1.083676, -2.081587, 1.57739, 3.04349] # shaft
    init_q: [4.810326, -0.555621, 1.086085, -2.100751, 1.577318, 3.042722] # bearing

    target_duration: 6
    target_pose_uncertain: False
    uncertainty_std: [0.001, 0.0]
    random_target_pose: False
    # target_pose: [0.1677, -0.4635, 0.46714, -0.00218, 0.00022, 1.0, 0.00066] # trapezoid
    # target_pose: [0.16794, -0.46202, 0.46714, -0.00218, 0.00022, 1.0, 0.00066] # star
    # target_pose: [0.1748921, -0.4613743, 0.4735147, -0.0032207, -0.0006325, 0.9999946, 0.0002698] # shaft
    target_pose: [0.1752261, -0.4610272, 0.4615621, -0.0032208, -0.0006339, 0.9999945, 0.0004608] # bearing
    # target_pose: [0.0542871, -0.4750609, 0.5039058, -0.0032545, 0.0002254, 0.9999947, 0.0001463] # pulley
    

    # Reward parameters
    tgt_pose_indices: [0,1,2,3,4,5]
    
    cumulative_episode_num: 0

    position_threshold: 0.002
    max_position_threshold: 0.005   # new 0.05
    orientation_threshold: 0.0349066
    max_orientation_threshold: 0.07

    reward_type: 'dense-distance-velocity-force'
    termination_on_negative_reward: True
    termination_reward_threshold: -450 # new -500

    cost:
        collision: -100.0
        done: 100
        step: -1.0  # new -1
    w_dist: 1.0
    w_force: 1.0
        
# Controller parameters
ur3e_force_control:
    max_twist: [0.025, 0.025, 0.025, 0.785398, 0.785398, 0.785398]

    max_force_torque: [30, 30.0, 30.0, 4, 4, 4]
    desired_force_torque: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
    # parallel control parameters
    pd_range_type: 'mult' # or 'sum'
    base_position_kp: [5.0, 5.0, 5.0, 50.0, 50.0, 100.0]
    kpd_range: 2
    base_force_kp: [0.01, 0.01, 0.015, 0.25, 0.25, 0.25]
    kpi_range: 3
    
    alpha: [0.5,0.5,0.5,0.5,0.5,0.5] # keep a degree of compliance

# # Controller parameters
# ur3e_force_control:
#     max_twist: [0.025, 0.025, 0.025, 0.785398, 0.785398, 0.785398]

#     max_force_torque: [30, 30.0, 30.0, 4, 4, 4]
#     desired_force_torque: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
#     # parallel control parameters
#     pd_range_type: 'mult' # or 'sum'
#     base_position_kp: [1.5, 1.5, 1.5, 50.0, 50.0, 100.0]
#     kpd_range: 2
#     base_force_kp: [0.005, 0.005, 0.005, 0.5, 0.5, 0.5]