ur3e_gym: #namespace
    # General Agent parameters
    env_id: "UR3ePegInHoleEnv-v1"
    controller_type: "parallel_position_force" # or "admittance"

    ft_sensor: True
    relative_to_ee: False
    robot_control_dt: 0.002
    agent_control_dt: 0.05
    reset_time: 2.0
    # actions parameters 
    n_actions: 12
    action_type: "motion_force"
    object_centric: True


    steps_per_episode: 500
    
    actor_class: "wave"
    ft_hist: True
    wrench_hist_size: 6
    duration_as_obs: True
    last_action_as_obs: True

    rand_seed: 10   
    rand_interval: 1

    randomize_board_properties: True
    board_initial_pose: [-0.10, 0.38, 0.13, 3.141592, 0, 0.0]
    board_workspace: [[-0.05, 0.05], [-0.05, 0.05], [-0.10, 0.0], [-30, 30], [-30, 30], [-60, 60]] # easy
    # board_workspace: [[-0.07, 0.0], [-0.05, 0.05], [0.0, 0.05], [-5, 5], [-5, 5], [-10, 10]] # mid
    # board_workspace: [[-0.07, 0.07], [-0.07, 0.07], [0.0, 0.05], [-10, 10], [-10, 10], [-90, 90]] # hard
    # max_board_workspace: [0.10, 0.10, 0.08, 10, 10, 45]
    max_board_workspace: [0.06, 0.06, 0.10, 30, 30, 60]
    min_board_workspace: [0.02, 0.02, 0.01, 0, 0, 20]
    curriculum_learning: True
    progressive_cl: True
    board_mu: 0.5
    board_mu2: 0
    board_stiffness: 1e5

    
    # initial conditions
    random_initial_pose: False
    # for each dimension define upper and lower bound from initial pose
    max_distance: [0.15, 0.15, 0.15, 0.785398, 0.785398, 1.5707]
    workspace: [[-0.1,0.1], [-0.1, 0.1], [0.0, 0.05], [20, -20], [20, -20], [20, -20]]
    init_q: [1.5045, -1.1956, 1.6012, -1.9544, -1.5742, -0.0636]

    target_duration: 6
    target_pose_uncertain: False
    uncertainty_std: [0.001, 0.0]
    random_target_pose: False
    target_pose: [-0.101, 0.40824, 0.14391, 0.7072, 0.70637, -0.00665, 0.02936]
    
    # Reward parameters
    target_dims: [0,1,2,3,4,5]
    
    cumulative_episode_num: 0

    position_threshold: 0.005
    max_position_threshold: 0.01
    orientation_threshold: 0.0349066
    max_orientation_threshold: 0.07

    reward_type: 'dense-distance-force'

    cost:
        collision: -500.0
        done: 150
    w_dist: 1.0
    w_force: 1.0
        
# Controller parameters
ur3e_force_control:
    max_twist: [0.05, 0.05, 0.05, 1.5707, 1.5707, 1.5707]

    max_force_torque: [50, 50.0, 50.0, 4, 4, 4]
    desired_force_torque: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
    # parallel control parameters
    pd_range_type: 'mult' # or 'sum'
    base_position_kp: [2.0, 2.0, 2.0, 50.0, 50.0, 50.0]
    kpd_range: 2
    base_force_kp: [1.0e-3, 1.0e-3, 1.0e-3, 0.5, 0.5, 0.5]
    kpi_range: 2
    
    alpha: [0.5,0.5,0.5,0.5,0.5,0.5] # keep a degree of compliance
