ur3e_gym: #namespace
    # General Agent parameters
    env_id: "UR3ePegInHoleEnv-v1"
    controller_type: "admittance"

    ft_sensor: True
    relative_to_ee: False
    robot_control_dt: 0.002
    agent_control_dt: 0.05
    reset_time: 2.0

    steps_per_episode: 500
    
    actor_class: "default"
    ft_hist: False
    duration_as_obs: True
    last_action_as_obs: True

    rand_seed: 10   
    rand_interval: 1

    randomize_board_properties: True
    board_initial_pose: [-0.10, 0.35, 0.10, 3.1415, 0, 0]
    board_workspace: [[-0.0, 0.0], [-0.0, 0.0], [0.0, 0.0], [-0, 0], [-0, 0], [-0, 0]] # easy
    # board_workspace: [[-0.07, 0.0], [-0.05, 0.05], [0.0, 0.05], [-5, 5], [-5, 5], [-10, 10]] # mid
    # board_workspace: [[-0.07, 0.07], [-0.07, 0.07], [0.0, 0.05], [-10, 10], [-10, 10], [-90, 90]] # hard
    board_mu: 0.5
    board_mu2: 0
    board_stiffness: 5e4

    
    # initial conditions
    random_initial_pose: False
    # for each dimension define upper and lower bound from initial pose
    workspace: [[-0.1,0.1], [-0.1, 0.1], [0.0, 0.05], [20, -20], [20, -20], [20, -20]]
    init_q: [1.5045, -1.1956, 1.6012, -1.9544, -1.5742, -0.0636]

    target_duration: 6
    target_pose_uncertain: False
    uncertainty_std: [0.001, 0.0]
    random_target_pose: False
    target_pose: [-0.101, 0.40824, 0.14391, 0.7072, 0.70637, -0.00665, 0.02936]
    # actions parameters 
    n_actions: 12
    action_type: "adm-guided" # "adm"
    
    # Reward parameters
    target_dims: [0,1,2,3,4,5]
    
    position_threshold: 0.01
    orientation_threshold: 0.1

    reward_type: 'dense-pdft'

    cost:
        collision: -100.0
        done: 150
    w_dist: 1.0
    w_force: 1.0
        
# Controller parameters
ur3e_force_control:
    n_actions: 12
    robot_control_dt: 0.002

    max_twist: [1.0, 1.0, 1.0, 0.7853, 0.7853, 0.7853]

    max_force_torque: [40.0, 40.0, 40.0, 4, 4, 4]
    desired_force_torque: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
    # parallel control parameters
    pd_range_type: 'mult' # or 'sum'
    base_position_kp: [2.0, 2.0, 2.0, 5.0, 5.0, 5.0]
    kpd_range: 2

    # Impedance control parameters
    impedance_method: "discretization"
    inertia_const: 1.0
    stiffness_const: [50000.0, 50000.0, 50000.0, 5000.0, 5000.0, 5000.0]
    damping_ratio: 0.001
    param_range: 80000
    
    alpha: [0.5,0.5,0.5,0.5,0.5,0.5] # keep a degree of compliance
